import Foundation
import CoreGraphics
import TrackpadFeature

func runTrackpadTests(_ t: TestRunner) {
    print("\n== Trackpad edge gestures ==")
    func point(_ x: Double, _ y: Double, _ id: Int32 = 1) -> EdgeTouch { EdgeTouch(id: id, x: x, y: y) }
    func pair(_ x: Double, _ y: Double, _ id: Int32 = 1) -> [EdgeTouch] {
        [point(x, y, id), point(x, y + 0.05, id + 100)]
    }
    func update(_ gesture: inout EdgeGesture, _ points: [EdgeTouch], _ time: Double, gain: Double = 1) -> EdgeGesture.Change? {
        gesture.update(points, at: time, width: 0.15, sensitivity: gain)
    }
    var gesture = EdgeGesture()
    t.expectTrue(update(&gesture, pair(0.05, 0.4), 0) == nil, "落指不立即调节")
    t.expectTrue(update(&gesture, pair(0.05, 0.4), 0.2) == nil, "停留确认不产生跳变")
    t.expectTrue(gesture.isArmed, "停留确认后即可锁住光标，不必等到第一次调节")
    let brighter = update(&gesture, pair(0.05, 0.45), 0.25)
    t.expectTrue(brighter?.side == .brightness && (brighter?.delta ?? 0) > 0, "左边上滑增大亮度")
    t.expectTrue(gesture.isControlling, "有效手势期间标记控制状态")
    let darker = update(&gesture, pair(0.05, 0.42), 0.3)
    t.expectTrue((darker?.delta ?? 0) < 0, "左边下滑减小亮度")
    _ = update(&gesture, [], 0.32)
    t.expectTrue(!gesture.isControlling, "抬手解除光标抑制")
    t.expectTrue(!gesture.isArmed, "抬手清除光标锁定条件")
    _ = update(&gesture, pair(0.95, 0.4), 1)
    _ = update(&gesture, pair(0.95, 0.4), 1.2)
    let louder = update(&gesture, pair(0.95, 0.45), 1.25)
    t.expectTrue(louder?.side == .volume && (louder?.delta ?? 0) > 0, "右边上滑增大音量")
    let softer = update(&gesture, pair(0.95, 0.4), 1.3)
    t.expectTrue((softer?.delta ?? 0) < 0, "右边下滑减小音量")

    gesture.reset()
    _ = update(&gesture, pair(0.5, 0.4), 0)
    _ = update(&gesture, pair(0.05, 0.4), 0.1)
    t.expectTrue(update(&gesture, pair(0.05, 0.5), 0.3) == nil, "从中间移入边缘不激活")
    gesture.reset()
    _ = update(&gesture, pair(0.05, 0.4), 0)
    _ = update(&gesture, pair(0.05, 0.5), 0.05)
    t.expectTrue(update(&gesture, pair(0.05, 0.6), 0.22) == nil, "没有停留的普通移动不激活")

    gesture.reset()
    _ = update(&gesture, pair(0.05, 0.4), 0)
    _ = update(&gesture, pair(0.05, 0.4), 0.2)
    t.expectTrue(update(&gesture, pair(0.05, 0.403), 0.21) == nil, "微小抖动不会调节")
    _ = update(&gesture, pair(0.05, 0.45), 0.25)
    _ = update(&gesture, pair(0.05, 0.5) + [point(0.1, 0.5, 2)], 0.3)
    t.expectTrue(!gesture.isControlling, "第三根手指立即终止控制")
    t.expectTrue(!gesture.isArmed, "多指操作清除光标锁定条件")
    t.expectTrue(update(&gesture, pair(0.05, 0.6), 0.4) == nil, "三指变双指不会重新触发直到全部抬手")

    gesture.reset()
    _ = update(&gesture, pair(0.05, 0.4), 0)
    _ = update(&gesture, pair(0.05, 0.4), 0.2)
    t.expectTrue(update(&gesture, pair(0.95, 0.5), 0.25) == nil, "跨边缘不会从亮度切到音量")
    gesture.reset()
    _ = update(&gesture, pair(0.05, 0.4), 0)
    _ = update(&gesture, pair(0.05, 0.4), 0.2)
    t.expectTrue(update(&gesture, pair(0.05, 0.5, 2), 0.25) == nil, "手指身份变化终止手势")
    gesture.reset()
    _ = update(&gesture, pair(0.05, 0.4), 0)
    _ = update(&gesture, pair(0.05, 0.4), 0.2)
    t.expectTrue(update(&gesture, pair(0.05, 0.8), 0.25) == nil, "坐标大幅跳变不调整")
    gesture.reset()
    _ = update(&gesture, pair(0.05, 0.4), 0)
    _ = update(&gesture, pair(0.05, 0.4), 0.2)
    let limited = update(&gesture, pair(0.05, 0.5), 0.25, gain: 2)
    t.expectTrue(abs(limited?.delta ?? 1) <= 0.08, "单帧变化最多 8%，避免突增")
    t.expectTrue(update(&gesture, pair(0.05, 0.6), 2) == nil && !gesture.isControlling, "断流后重新确认手势")
    t.expectTrue(update(&gesture, pair(.nan, 0.4), 2.1) == nil, "无效坐标被忽略")

    var devices = DeviceGestures()
    func deviceUpdate(_ id: UInt64, _ points: [EdgeTouch], _ time: Double, native: Double? = nil) -> EdgeGesture.Change? {
        devices.update(deviceID: id, touches: points, at: native ?? time,
                       receivedAt: time, width: 0.15, sensitivity: 1)
    }
    _ = deviceUpdate(1, pair(0.05, 0.4), 0)
    _ = deviceUpdate(2, pair(0.95, 0.4), 0.1, native: 50)
    t.expectTrue(!devices.isArmed, "两块设备相同手指编号不合并停留时间")
    _ = deviceUpdate(1, pair(0.05, 0.4), 0.2)
    t.expectEqual(devices.activeDeviceID, UInt64(1), "内置触摸板独立确认并获得控制权")
    _ = deviceUpdate(2, [], 0.21, native: 500)
    t.expectTrue(devices.isArmed, "外接抬手和不同时间戳不解除内置光标锁定")
    let internalChange = deviceUpdate(1, pair(0.05, 0.45), 0.25)
    t.expectTrue(internalChange?.side == .brightness, "内置调节不受外接空帧影响")
    t.expectTrue(deviceUpdate(2, pair(0.95, 0.7), 0.26) == nil, "另一块触摸板不能抢占调节")
    _ = deviceUpdate(1, [], 0.27)
    t.expectTrue(!devices.isArmed, "当前控制设备抬手释放光标")
    _ = deviceUpdate(2, pair(0.95, 0.7), 0.5)
    t.expectTrue(!devices.isArmed, "已落在另一块设备上的手指必须先抬起再激活")
    _ = deviceUpdate(2, [], 0.51)
    _ = deviceUpdate(2, pair(0.95, 0.4), 0.6)
    _ = deviceUpdate(2, pair(0.95, 0.4), 0.8)
    t.expectTrue(deviceUpdate(2, pair(0.95, 0.45), 0.85)?.side == .volume, "外接触摸板随后可以正常调音量")
    _ = deviceUpdate(1, [], 1.1)
    t.expectTrue(devices.expire(at: 1.16) && !devices.isArmed, "另一块设备持续送帧不能延长断流设备的光标锁定")
    _ = deviceUpdate(2, [], 1.2)
    _ = deviceUpdate(2, pair(0.95, 0.4), 1.3)
    _ = deviceUpdate(2, pair(0.95, 0.4), 1.5)
    devices.cancelUntilLift()
    _ = deviceUpdate(2, pair(0.95, 0.45), 1.55)
    t.expectTrue(!devices.isArmed, "点击或硬件错误后同一设备抬手前不会重新调节")
    devices.reset()
    _ = deviceUpdate(1, pair(0.5, 0.4), 2)
    _ = deviceUpdate(2, [], 2.01)
    _ = deviceUpdate(1, pair(0.05, 0.4), 2.1)
    _ = deviceUpdate(1, pair(0.05, 0.4), 2.3)
    t.expectTrue(!devices.isArmed, "另一块设备空帧不会清除从中间移入边缘的拒绝状态")

    gesture.reset()
    _ = update(&gesture, [point(0.05, 0.4)], 0)
    _ = update(&gesture, [point(0.05, 0.4)], 0.2)
    t.expectTrue(update(&gesture, [point(0.05, 0.45)], 0.25) == nil && !gesture.isArmed, "单指停留和滑动均不调节")
    t.expectTrue(update(&gesture, pair(0.05, 0.45), 0.26) == nil && !gesture.isArmed, "单指移动后加第二指不会激活")
    gesture.reset()
    _ = update(&gesture, [point(0.05, 0.4)], 0)
    _ = update(&gesture, pair(0.05, 0.4), 0.04)
    _ = update(&gesture, pair(0.05, 0.4).reversed(), 0.24)
    t.expectTrue(gesture.isArmed, "允许两指先后落下，触点数组顺序改变不影响识别")
    _ = update(&gesture, [point(0.05, 0.4)], 0.25)
    t.expectTrue(!gesture.isArmed, "抬起任意一指立即释放控制")
    _ = update(&gesture, pair(0.05, 0.4), 0.26)
    t.expectTrue(!gesture.isArmed, "抬一指后放回必须全部抬手才重启")
    gesture.reset()
    _ = update(&gesture, [point(0.05, 0.4), point(0.95, 0.45, 2)], 0)
    _ = update(&gesture, [point(0.05, 0.4), point(0.95, 0.45, 2)], 0.2)
    t.expectTrue(!gesture.isArmed, "两根手指跨左右边缘不激活")
    gesture.reset()
    _ = update(&gesture, [point(0.05, 0.4), point(0.5, 0.45, 2)], 0)
    _ = update(&gesture, pair(0.05, 0.4), 0.2)
    t.expectTrue(!gesture.isArmed, "第二指从中间滑进边缘不激活")

    let suiteName = "MacToolsTest.trackpad.\(UUID().uuidString)"
    let defaults = UserDefaults(suiteName: suiteName)!
    defer { defaults.removePersistentDomain(forName: suiteName) }
    let controller = TrackpadController(defaults: defaults)
    t.expectTrue(!controller.enabled && !controller.isRunning, "默认关闭且创建设置视图不会启动硬件")
    controller.edgeWidth = 0.2
    controller.sensitivity = 1.5
    let reloaded = TrackpadController(defaults: defaults)
    t.expectEqual(reloaded.edgeWidth, 0.2, "边缘宽度持久化")
    t.expectEqual(reloaded.sensitivity, 1.5, "灵敏度持久化")

    var pointer = CGPoint(x: 100, y: 200)
    var warps: [CGPoint] = []
    let lock = CursorLock(position: { pointer }, warp: { warps.append($0); return true })
    t.expectTrue(lock.setLocked(true) && lock.isLocked, "调节开始时记录光标位置")
    pointer = CGPoint(x: 300, y: 400)
    _ = lock.setLocked(true)
    _ = lock.holdPosition()
    _ = lock.holdPosition()
    t.expectEqual(warps, [CGPoint(x: 100, y: 200), CGPoint(x: 100, y: 200)], "移动事件始终保持开始调节时的位置")
    _ = lock.setLocked(false)
    _ = lock.holdPosition()
    t.expectTrue(!lock.isLocked && warps.count == 2, "抬手后不再约束光标")
    _ = lock.setLocked(true)
    _ = lock.holdPosition()
    t.expectEqual(warps.last, pointer, "新手势使用新的光标位置，不跳回旧位置")
    _ = lock.setLocked(false)
    let unavailableLock = CursorLock(position: { nil }, warp: { _ in true })
    t.expectTrue(!unavailableLock.setLocked(true) && !unavailableLock.isLocked, "无法读取位置时取消锁定")
    let failedWarp = CursorLock(position: { pointer }, warp: { _ in false })
    _ = failedWarp.setLocked(true)
    t.expectTrue(!failedWarp.holdPosition(), "固定位置失败会报告给事件监听以取消本次调节")
    _ = failedWarp.setLocked(false)
    t.expectTrue(!failedWarp.isLocked, "固定位置失败后仍能释放锁定")
}
